# Timeline Constants
BRANCH_NAME_LEN = 100
BRANCH_DESCRIPTION_LEN = 200

STORY_TITLE_LEN = 40
STORY_DESCRIPTION_LEN = 40
STORY_TEXT_LEN = 500

MAP_TITLE_LEN = 200
MAP_BASE_FOLDER_LEN = 20
MAP_AUTHOR_LEN = 200

# Timeline API Constants
STORY_RESOURCE_LIMIT = 100
