# Quest Constants

QUESTSET_TITLE_LEN = 200
QUESTSET_DESC_LEN = 600

QUEST_TITLE_LEN = 200

TASK_TITLE_LEN = 200
TASK_CODE_LEN = 400
TASK_TYPES = ('BiblioCommons Content Creation', 'Social Media Sharing', 'Submittable Codes', 'TimeMap Exploration')
TASK_CHOICES = ((0, TASK_TYPES[0]), (1, TASK_TYPES[1]), (2, TASK_TYPES[2]), (3, TASK_TYPES[3]))
TASK_BIBLIOCOMMONS = 0
TASK_SOCIAL = 1
TASK_CODE = 2
TASK_TIMEMAP = 3

MAX_ACTIVE_QUESTS = 5
MAX_POINTS = 6000
