# Quest Constants

QUESTSET_TITLE_LEN = 200
QUESTSET_DESC_LEN = 600

QUEST_TITLE_LEN = 200

TASK_TITLE_LEN = 200
TASK_DESC_LEN = 400
TASK_CODE_LEN = 400
TASK_TYPES = ('BIBLIOCONTENT', 'BIBLIOLIST', 'SOCIALMEDIA', 'CODE')